### ISSUE TITLE
Connection to Salesforce Instances that use a custom Domain / URL are not possible

### ISSUE THREAD

**Issue by dade-murphy** [kevinohara80/nforce#80]
They LOGIN_URI, TEST_LOGIN_URI,  can be overridden in the constructor, but he AUTH_ENDPOINT /  TEST_AUTH_ENDPOINT can't  and this is a hard break for any SF instance that has been moved to the MyDomain URL options.

**Comment by kevinohara80** [comment]
Basically, `getAuthUri()` is just a helper function to construct the URL that you should redirect your application to in order to kick off the OAuth flow. It's the only part of the module that uses `AUTH_ENDPOINT` or `TEST_AUTH_ENDPOINT`. It's pretty easy to just create the URL yourself for now. 

But that said, yeah, this could be added into nforce. It would be pretty easy to allow this as a configuration option. I'll get to this as soon as I can but I'll also take a PR too. ;)

**Comment by kevinohara80** [comment]
Ended up having to cut another beta so I went ahead and implemented this. Look for the new configuration options when creating a connection (`authEndpoint` and `testAuthEndpoint`).
