### ISSUE TITLE
User-Agent Flow

### ISSUE THREAD

**Issue by michacom** [kevinohara80/nforce#90]
Would you like to provide a minimalist example using the flow.

IMHO, the functionality seems to be broken...

**Comment by kevinohara80** [comment]
The user-agent flow returns the access token as part of the url in the redirection. Therefore, your application must pull the access token out of the url. nforce just helps you to construct the uri that you navigate to in order to start the auth flow with Salesforce.

After authenticating, Salesforce will redirect to your callback endpoint with a url like this. Note, for security, the access token is after a `#` versus a `?`

```
https://www.mysite.com/user_callback.jsp#access_token=00Dx0000000BV7z%21A
R8AQBM8J_xr9kLqmZIRyQxZgLcM4HVi41aGtW0qW3JCzf5xdTGGGSoVim8FfJkZEqxbjaFbbe
rKGk8v8AnYrvChG4qJbQo8&refresh_token=5Aep8614iLM.Dq661ePDmPEgaAW9Oh_L3JKk
DpB4xReb54_pZfVti1dPEk8aimw4Hr9ne7VXXVSIQ%3D%3D&instance_url=https%3A%2F%
2Fna1.salesforce.com&id=https%3A%2F%2Flogin.salesforce.com%2Fid%2F00Dx000
0000BV7z%2F005x00000012Q9P&issued_at=1278448101416&signature=miQQ1J4sdMPi
duBsvyRYPCDozqhe43KRc1i9LmZHR70%3D&scope=id+api+refresh_token&token_type=
Bearer&state=mystate
```

So in express, I'd just write something simple like this using `querystring` for my callback handler...

```
var qs = require('querystring');

app.get('/user_callback', function(req, res) {
  var oauth = qs.parse(req.url.split('#')[1]);
  res.end();
});
```

**Comment by michacom** [comment]
sorryMyBad. I did not understand this flow purpose. The hash part does not posts to server, so I had to use WebServer Flow - works fine.
