### ISSUE TITLE
Fetch all data from SF

### ISSUE THREAD

**Issue by Laboratory** [kevinohara80/nforce#95]
Hello,

I sync all data from SF. Can you implement executing callback when I got part of data:
`````javascript
if(opts.fetchAll && resp.nextRecordsUrl) {
        //run handleResults for store part of data
        self.getUrl({ url: resp.nextRecordsUrl, oauth: opts.oauth }, handleResults);
}...
`````

**Comment by kevinohara80** [comment]
I'm not sure I totally understand your question. If you're looking to get a callback between each API call, you could just implement this yourself by calling `query()` without the `fetchAll` argument and then calling `getUrl()` for getting subsequent sets of records. It's basically what `fetchAll` is doing under the covers.

`fetchAll` is just a convenience and not right for every situation because it essentially buffers up the entire set of records in memory. If you're dealing with a large set of data it could be problematic.

**Comment by Laboratory** [comment]
I have a problem with a large set of data, I got exception `Out of memory`. I'll try calling `query` with `getUrl`.

Thx
